/* =====================================================
   sync-hero.js
   Scans images/hero/ and generates data/hero-slides.js
   and data/hero-slides.json

   HOW TO USE:
     1. Put any images you want in the hero into images/hero/
        Tip: name them 01-, 02-, 03-... to control the order
     2. Run: node sync-hero.js
     3. Refresh the site

   Supported formats: .jpg  .jpeg  .png  .webp  .gif
   ===================================================== */

const fs   = require('fs');
const path = require('path');

const HERO_DIR = path.join(__dirname, 'images', 'hero');
const OUT_JSON = path.join(__dirname, 'data', 'hero-slides.json');
const OUT_JS   = path.join(__dirname, 'data', 'hero-slides.js');

const SUPPORTED = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];

// Read folder, filter to image files, sort alphabetically (01-, 02-... ordering)
const files = fs.readdirSync(HERO_DIR)
  .filter(f => SUPPORTED.includes(path.extname(f).toLowerCase()))
  .sort()
  .map(f => 'images/hero/' + f);

if (!files.length) {
  console.warn('⚠️  No images found in images/hero/ — add some images and run again.');
  process.exit(0);
}

// Write JSON (used by fetch over HTTP)
fs.writeFileSync(OUT_JSON, JSON.stringify(files, null, 2));

// Write JS (used as file:// fallback)
fs.writeFileSync(OUT_JS,
  '/* Auto-generated by sync-hero.js — do not edit manually */\n' +
  'window.HERO_SLIDES = ' + JSON.stringify(files, null, 2) + ';\n'
);

console.log('✅  Hero slides updated — ' + files.length + ' image(s):');
files.forEach(function(f) { console.log('   · ' + f); });
